backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "ข้อมูลหน้าเว็บ"
    files:
      - file: "content.json"
        label: "รายละเอียดบ้านพัก"
        name: "home"
        format: json
        fields:
          - { label: "ชื่อบ้านพัก", name: "title", widget: "string" }
          - { label: "คำโปรย", name: "description", widget: "text" }
          - { label: "ราคาต่อคืน", name: "price", widget: "number" }
          - { label: "รูปหน้าปก", name: "hero_image", widget: "image" }